[package]
name = "texbox"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.1"
bevy = { version = "0.15.3", features = ["exr"] }
bevy_asset_loader = "0.22.0"
bevy_skein = "0.1.2"
serde_json = "1.0.140"